# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'


variables:
  LT_USERNAME: 'varunkumarb'
  LT_ACCESS_KEY: 'GhGShOYHz1jODWE9qDvkJK4nPDR3n2lc0gNp9VknalhwtUineG'
  LT_BUILD_NAME: 'Azure_testng_demo'

# Maven
steps:
- task: configuration@1
  inputs:
    connection: 'tunnelVarun'
    tunnelOptions: '{"verbose": true, "allowHosts": "lambdatest.com", "logfile": "a.log"}'
    isTunnelActivate: true

- script: |
    echo Executing curl upload...
    curl -vvv lambdatest.com
  displayName: 'Checking accessibility of the application'

- script: mvn test -P android-single
  displayName: 'Run Android Tests'

- task: LambdatestResults@1
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '273b3140-3faa-4ec6-a9ed-f121e7f8f457'
    definition: '15'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    artifactName: 'tunnel_log'
    targetPath: '$(Pipeline.Workspace)/a.log'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  continueOnError: true
  condition: always()
  retryCountOnTaskFailure: 1
