# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'


variables:
  LT_USERNAME: 'varunkumarb'
  LT_ACCESS_KEY: 'GhGShOYHz1jODWE9qDvkJK4nPDR3n2lc0gNp9VknalhwtUineG'
  LT_BUILD_NAME: 'Azure_testng_demo'

# Maven
steps:
- task: configuration@1
  inputs:
    connection: 'tunnelVarun'
    isTunnelActivate: true
    tunnelOptions: 'Varun'
- script: mvn test -P android-single
  displayName: 'Run Android Tests'

- task: LambdatestResults@1
